### ISSUE TITLE
Support for MonetaryAccountBankSavings is missing

### ISSUE THREAD

**Issue by basst85** [bunq/sdk_java#113]
## Steps to reproduce:
1. The method MonetaryAccount.get(..).getMonetaryAccountSavings() is not available.

## What should happen:
1.The method MonetaryAccount.get(..).getMonetaryAccountSavings() should be available.

## What happens:
1. The method MonetaryAccount.get(..).getMonetaryAccountSavings() is not available.

## SDK version and environment
- Tested on [1.1.0](https://github.com/bunq/sdk_java/releases/tag/1.1.0)
- [x] Sandbox
- [x] Production

**Comment by reckter** [comment]
Can we get an ETA on when this will come? I build a personal project with the api, but right now I can not use it, because Saving accounts are not supported yet :/

**Comment by OGKevin** [comment]
its sad, all it takes is to regenerate the SDK :(. 

I would say spam them on together like i did: https://together.bunq.com/d/5398-savings-account-has-been-added-to-the-pub-api

**Comment by reckter** [comment]
Seems like they generated the code now :)

**Comment by basst85** [comment]
Fixed in 1.10.0 (tested in Android Studio)
