### ISSUE TITLE
Certificate pinning issue after bunq certificate renewal

### ISSUE THREAD

**Issue by erwindeg** [bunq/sdk_java#115]
## Steps to reproduce:
1. Create a BunqContext with the Java SDK

## What should happen:
1. Session should be successfully created and payments should succeed

## What happens:
1.  Creation fails with com.bunq.sdk.exception.UncaughtExceptionError: Uncaught exception "Certificate pinning failure!"

## SDK version and environment
- Tested on [1.1.0](https://github.com/bunq/sdk_java/releases/tag/1.1.0)
- [ X ] Sandbox
- [ ] Production

## Extra info:
It looks like your certificate for https://public-api.sandbox.bunq.com/ was renewed last night and now the hardcoded pinned key in the SDK doesn't match the key of the new certificate

**Comment by OGKevin** [comment]
waw 🤦‍♂️ 👏, lets hope that they will be more careful when doing this on prod.

**Comment by erwindeg** [comment]
This should be the new value:
sha256/9Y+oZve6H+r17Kdn+lN5sT0ijgxLyDGIuQtUwLupawA=

**Comment by OGKevin** [comment]
> This should be the new value:
> sha256/9Y+oZve6H+r17Kdn+lN5sT0ijgxLyDGIuQtUwLupawA=

A nice, create a pull request I would say 😊 Also, it would be a good idea to add a comment in the code in https://github.com/bunq/sdk_java/blob/f3818e3380b472cafd1dbe69bf45a78434f54c84/src/main/java/com/bunq/sdk/context/ApiEnvironmentType.java on the command to run to update it 😊

**Comment by erwindeg** [comment]
Yes, I just did :)

**Comment by mwlynch** [comment]
FYI: This is how we got the new value.
Run this and grab the new key from the log output.

```java
        String hostname = "public-api.sandbox.bunq.com";

        CertificatePinner certificatePinner = new CertificatePinner.Builder()
                .add(hostname, "sha256/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=")
                .build();

        OkHttpClient client = new OkHttpClient.Builder()
                .certificatePinner(certificatePinner)
                .build();

        Request request = new Request.Builder()
                .url("https://" + hostname)
                .build();
        client.newCall(request).execute();
    }
}
```

**Comment by OGKevin** [comment]
hmm, I used to use the openssl command to get this. That was the command I was referring tho. Interesting method however :P

**Comment by mwlynch** [comment]
There, I figured it out :-P

openssl s_client -connect sandbox.bunq.com:443 -showcerts < /dev/null 2> /dev/null | openssl x509 -pubkey -noout | openssl enc -base64 -d | openssl dgst -sha256 -binary | openssl enc -base64
