### ISSUE TITLE
Certificate pinning issue after bunq certificate renewal

### ISSUE THREAD

**Issue by masoudparvari** [bunq/sdk_java#123]
## Steps to reproduce:
1. Create a BunqContext with the Java SDK

## What should happen:
1. Session should be successfully created and payments should succeed

## What happens:
1. Creation fails with com.bunq.sdk.exception.UncaughtExceptionError: Uncaught exception "Certificate pinning failure!"

## SDK version and environment
- Tested on [1.13.0](https://github.com/bunq/sdk_java/releases/tag/1.13.0)
- [X] Sandbox
- [ ] Production

## Extra info:
Apparently your old certificate has expired in Wednesday, 21 April 2021 at 14:00:00. And that's hard coded in code.

**Comment by GionaGranchelli** [comment]
same problem here

**Comment by saket88** [comment]
Any details about the fix of this issue?

**Comment by DrOof** [comment]
Is the problem just the pinned key? 

`SANDBOX(
      "public-api.sandbox.bunq.com",
      "v1",
      "sha256/9Y+oZve6H+r17Kdn+lN5sT0ijgxLyDGIuQtUwLupawA="
  );`

**Comment by masoudparvari** [comment]
> Is the problem just the pinned key?
> 
> ```
> SANDBOX(
>       "public-api.sandbox.bunq.com",
>       "v1",
>       "sha256/9Y+oZve6H+r17Kdn+lN5sT0ijgxLyDGIuQtUwLupawA="
>   );
> ```

yes, this should be new ky: 
sha256/SEJfjAW74vHQmGe/lb9NwBjzAw5y7rpJH3UWpGE5q8A=

**Comment by DrOof** [comment]
Sweet. Should we do a PR? Or is this already planned for a release?

**Comment by DrOof** [comment]
I have a patch for ourselves. But I can't push a branch and do a pull request.

**Comment by NickvandeGroes** [comment]
Hi guys! Thanks for bringing this up :) 

To enable you to keep using our SDKs, a PR has been submitted just now that will update the certificate hash. I'll close this issue when the PR is merged so you know when you can continue building great applications with our amazing API!
