### ISSUE TITLE
OauthAuthorizationUri creates incorrect URL

### ISSUE THREAD

**Issue by Nayels** [bunq/sdk_java#126]
## Steps to reproduce:
1. Create `OauthAuthorizationUri` with state

## What should happen:
`https://oauth.bunq.com/auth?response_type=code&redirect_uri=redirecturi&client_id=client_id&state=state`

## What happens:
No `&` that divides the `client_id` and `state` parameters resulting in incorrect hash for `clientId`.

The URL should be: 
`https://oauth.bunq.com/auth?response_type=code&redirect_uri=redirecturi&client_id=client_idstate=state`

## SDK version and environment
- Tested on [1.13.1](https://github.com/bunq/sdk_java/releases/tag/1.13.1)

**Comment by angelomelonas** [comment]
Hi @Nayels, 

Thanks for raising this issue! 🙏🏼 I see we already have a [pending PR](https://github.com/bunq/sdk_java/pull/129) for it. This will be fixed in the upcoming release (1.14.1).
