### ISSUE TITLE
Clean dependencies

### ISSUE THREAD

**Issue by patrickdw1991** [bunq/sdk_java#25]
Currently the bunq java sdk uses dependencies like:

Guava: Really big lib which is only used for nullability annotations.
Alternative for nullability annotations: https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305

Commons-io: Currently using a really out-dated commons-io.
Alternative use newer: https://mvnrepository.com/artifact/commons-io/commons-io

Appache httpclient: Just doesn't really work well with android
Alternative: Okhttp

**Comment by OGKevin** [comment]
Hey @patrickdw1991,

Thanks for these suggestions, will take a look and see if we can use these indeed 👍

**Comment by OGKevin** [comment]
Guava will be removed for 0.12.4
