### ISSUE TITLE
Response is missing response headers and pagination

### ISSUE THREAD

**Issue by dnl-blkv** [bunq/sdk_java#4]
# How to Reproduce
1. Make a valid listing request to bunq API via the Java SDK
2. Make a valid get/put/post/delete request to bunq API via the Java SDK

# What Should Happen
1. The response contains response headers and pagination
2. The response contains response headers

# What Happens
1. The response does not contain response header nor pagination
2. The response does not contain response header

# Notes
1. The structural fix would be to introduce `BunqResponse` object which, besides the response model, includes the response headers and pagination

**Comment by OGKevin** [comment]
Closing I favour of #5

**Comment by dnl-blkv** [comment]
@OGKevin but pagination is sill not in!

**Comment by OGKevin** [comment]
Ah, i was closing all the issue in the milestone 😊.

0.11.0 ?

**Comment by dnl-blkv** [comment]
Yes please! :)

**Comment by OGKevin** [comment]
Closing in favour of #13
