### ISSUE TITLE
Add java 7 compatibility 

### ISSUE THREAD

**Issue by OGKevin** [bunq/sdk_java#42]
## Steps to reproduce:
1. Most android SDK's don't support java 8 
2. Try to use the bunq sdk on one of these android sdk's

## What should happen:
1. It works smoothly 

## What happens:
1. A bunch of errors 

## Logs

```
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\lenvovo\.gradle\caches\modules-2\files-2.1\com.github.bunq\sdk_java\b5c97e4\e70d9e73b467b9e46cd315e2d40182b175385b38\sdk_java-b5c97e4.jar

Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing com/bunq/sdk/security/SecurityUtils.class

Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.

> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\lenvovo\.gradle\caches\modules-2\files-2.1\com.github.bunq\sdk_java\b5c97e4\e70d9e73b467b9e46cd315e2d40182b175385b38\sdk_java-b5c97e4.jar
```

## Extra info:
- Tested on [0.12.3](https://github.com/bunq/sdk_java/releases/tag/0.12.3)

**Comment by tubbynl** [comment]
if this is a thing you can set `sourceCompatibility = 1.7` in `build.gradle`

this project does contain some java8 here and there :)

**Comment by tubbynl** [comment]
if u want i can create a branch from add_java_7_support_bunq/sdk_java#42 and fix that

but it will probably only make sense to also merge / sync some pending pull requests before that and/or i'll merge them for you in one pull request @OGKevin

**Comment by OGKevin** [comment]
I've already started working on this, feel free to finish it however. You can do this by creating your own branch as child of my branch which is https://github.com/bunq/sdk_java/compare/add_java_7_support_bunq/sdk_java%2342 and then create a PR that merges into my branch. Afterwards this gets merged in develop.
